FROM node:22-alpine3.19
WORKDIR /home/app

RUN npm install pnpm -g
COPY package.json .

RUN pnpm install

COPY . .

RUN pnpm run build
RUN mkdir dist/public
RUN cp ./src/public/* ./dist/public
CMD ["pnpm", "run", "start"]